// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2_AP1_JoseOrtega.DAL;

#nullable disable

namespace P2_AP1_JoseOrtega.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251103224044_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("P2_AP1_JoseOrtega.Models.Componente", b =>
                {
                    b.Property<int>("ComponenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("ComponenteId");

                    b.ToTable("Componentes");

                    b.HasData(
                        new
                        {
                            ComponenteId = 1,
                            Descripcion = "Memoria 4GB",
                            Existencia = 1,
                            Precio = 1580m
                        },
                        new
                        {
                            ComponenteId = 2,
                            Descripcion = "Disco SSD 120MB",
                            Existencia = 8,
                            Precio = 4200m
                        },
                        new
                        {
                            ComponenteId = 3,
                            Descripcion = "Tarjeta de Video",
                            Existencia = 4,
                            Precio = 10000m
                        });
                });

            modelBuilder.Entity("P2_AP1_JoseOrtega.Models.Pedidos", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PedidoId");

                    b.ToTable("pedidos");
                });

            modelBuilder.Entity("P2_AP1_JoseOrtega.Models.PedidosDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponenteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("ComponenteId");

                    b.HasIndex("PedidoId");

                    b.ToTable("detalles");
                });

            modelBuilder.Entity("P2_AP1_JoseOrtega.Models.PedidosDetalle", b =>
                {
                    b.HasOne("P2_AP1_JoseOrtega.Models.Componente", "componentes")
                        .WithMany("pedidosDetalle")
                        .HasForeignKey("ComponenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P2_AP1_JoseOrtega.Models.Pedidos", "pedidos")
                        .WithMany("pedidosDetalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("componentes");

                    b.Navigation("pedidos");
                });

            modelBuilder.Entity("P2_AP1_JoseOrtega.Models.Componente", b =>
                {
                    b.Navigation("pedidosDetalle");
                });

            modelBuilder.Entity("P2_AP1_JoseOrtega.Models.Pedidos", b =>
                {
                    b.Navigation("pedidosDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
